apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  db-root-password: cm9vdHBhc3M=
  user: bGFsYQ== # lala
  user-password: bGFsYTIwMjA= # lala2020

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cfgmap
data:
  db_name: Test_db