apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  db-root-password: cm9vdHBhc3M=
  user: cm9vdA== # root
  user-password: cm9vdHBhc3M= # rootpass

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cfgmap
data:
  db_name: Test_db