apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: test-6
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root_passwd
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user_passwd
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: db_name
                  name: mysql-cfgmap
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
