apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: test-6
  labels:
    app: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        version: "1"
        app: wordpress
      namespace: test-6
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: db_host
                  name: mysql-cfgmap
            - name: WORDPRESS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: db_name
                  name: mysql-cfgmap
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: mysql-secret
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: user_passwd
                  name: mysql-secret
